language: python
sudo: true
python:
  - "3.6"

install:
  - CODECOV_TOKEN="fa9cb0a3-2c26-48c8-9e18-b5abc901e28c"
  - pip install -r requirements.txt > /dev/null
  - pip install codecov

script:
  - coverage run run_tests.py

after_success:
  - codecov --token=$CODECOV_TOKEN